"""empty message

Revision ID: 26ba9deaa74e
Revises: 
Create Date: 2021-07-08 20:09:15.720222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ba9deaa74e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('identity', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('theme', sa.String(length=64), nullable=True),
    sa.Column('commit_time', sa.DateTime(), nullable=True),
    sa.Column('commit_user', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('photo_url', sa.String(length=64), nullable=True),
    sa.Column('photo_time', sa.DateTime(), nullable=True),
    sa.Column('describeinfo', sa.String(length=64), nullable=True),
    sa.Column('copyrightnum', sa.Integer(), nullable=True),
    sa.Column('opinion', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['commit_user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('copyrightnum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('users')
    # ### end Alembic commands ###
